### ISSUE TITLE
Application crashes when hovering over 'Connection' menu

### ISSUE THREAD

**Issue by sebastianrode** [kaktus85/Hameg8118#2]
As soon as I hover over the 'Connection' menu the application crashes. All other buttons/menus can be clicked without issues. However, without being able to use the connection menu the application can't be used at all.

I already tried to launch it in compatibility mode. This did not yield success.

Looking forward to hints on how to get the application useable.

**Comment by kaktus85** [comment]
Hi Sebastian, unfortunately, I don't have access to the machine anymore. I
used to work with Hameg 8118 during my university studies.
I tried to at least compile and run the program using Visual Studio 2022
and it does run and does not crash when I click on "Connection" but that is
all I can do without the actual machine.

pá 18. 10. 2024 v 22:41 odesílatel sebastianrode ***@***.***>
napsal:

**Comment by sebastianrode** [comment]
I reinstalled .NET and then the problem was solved. The application works as expected.
Nevertheless, thank you very much for your quick response.
